<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:Api" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:Api">
<types>
<xsd:schema targetNamespace="urn:Api">
<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
</xsd:schema>
</types>
<message name="set_egresoRequest">
<part name="egreso" type="xsd:string"/>
<part name="apikey" type="xsd:string"/>
</message>
<message name="set_egresoResponse">
<part name="return" type="xsd:string"/>
</message>
<portType name="ApiPortType">
<operation name="set_egreso">
<documentation>La siguiente funcion recibe un archivo y transfiere los datos al servidor</documentation>
<input message="tns:set_egresoRequest"/>
<output message="tns:set_egresoResponse"/>
</operation>
</portType>
<binding name="ApiBinding" type="tns:ApiPortType">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
<operation name="set_egreso">
<soap:operation soapAction="urn:Api#set_egreso" style="rpc"/>
<input>
<soap:body use="encoded" namespace="urn:Api" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</input>
<output>
<soap:body use="encoded" namespace="urn:Api" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</output>
</operation>
</binding>
<service name="Api">
<port name="ApiPort" binding="tns:ApiBinding">
<soap:address location="http://localhost/resttouch/wms.php/api"/>
</port>
</service>
</definitions>